name: Metrics
on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: metrics.svg
          user: WuChenDi
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          config_twemoji: yes
